# Generated by Django 4.1.2 on 2022-10-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(null=True, to='api.person'),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1024)),
                ('instruction', models.CharField(max_length=1024)),
                ('responsible', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='api.person')),
                ('users', models.ManyToManyField(null=True, to='api.person')),
            ],
        ),
    ]
