# Generated by Django 4.1.2 on 2022-10-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_achievement_description_achievement_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wallet'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='api.person'),
        ),
    ]
